/*Creamos las tablas*/
CREATE TABLE EMPLEADOS(
	LEGAJO INT NOT NULL,
	NOMBRE VARCHAR (20) NOT NULL,
	DOMICILIO VARCHAR (20) NOT NULL,
	LOCALIDAD VARCHAR (30) NOT NULL,
	CODIGO INT NOT NULL,
	PRIMARY KEY(LEGAJO));
	
CREATE TABLE DEPARTAMENTOS(
	CODIGO INT NOT NULL,
	DESCRIPCION VARCHAR (20) NOT NULL,
	PRIMARY KEY(CODIGO));
	
	
/* Agregamos las claves foraneas*/
ALTER TABLE empleados ADD CONSTRAINT CODIGO FOREIGN KEY(CODIGO)
REFERENCES departamentos (CODIGO) ON DELETE CASCADE;
	
/*Cargamos las tablas*/
INSERT INTO EMPLEADOS(LEGAJO, NOMBRE, DOMICILIO, LOCALIDAD, CODIGO) VALUES (101, "Gómez", "Nazca 920", "Capital Federal", 102);
INSERT INTO EMPLEADOS(LEGAJO, NOMBRE, DOMICILIO, LOCALIDAD, CODIGO) VALUES (102, "Pérez", "Argerich 1030", "Capital Federal", 100);
INSERT INTO EMPLEADOS(LEGAJO, NOMBRE, DOMICILIO, LOCALIDAD, CODIGO) VALUES (103, "Vázquez", "Sarmiento 450", "Ramos Mejía", 102);
INSERT INTO EMPLEADOS(LEGAJO, NOMBRE, DOMICILIO, LOCALIDAD, CODIGO) VALUES (104, "López", "Alsina 720", "Avellaneda", 101);

INSERT INTO DEPARTAMENTOS(CODIGO, DESCRIPCION) VALUES (100, "RRHH");
INSERT INTO DEPARTAMENTOS(CODIGO, DESCRIPCION) VALUES (101, "Finanzas");
INSERT INTO DEPARTAMENTOS(CODIGO, DESCRIPCION) VALUES (102, "Sistemas");
INSERT INTO DEPARTAMENTOS(CODIGO, DESCRIPCION) VALUES (103, "Tesoreria");



/* Agregamos a la tabla  llamada productos la columna IMPORTADOR*/

/*CREAMOS LA TABLA PRODUCTOS*/
CREATE TABLE PRODUCTOS(
	PNRO INT NOT NULL,
	PNOMBRE VARCHAR(20) NOT NULL,
	PRECIO FLOAT NOT NULL,
	TAMANO VARCHAR(10) NOT NULL,
	LOCALIDAD VARCHAR(30) NOT NULL,
	PRIMARY KEY(PNRO));
	
	
/*AGREGAMOS LA COLUMNA*/
ALTER TABLE PRODUCTOS ADD COLUMN IMPORTADOR VARCHAR(20) NOT NULL;



/* Eliminamos la tabla clientes */
/*CREAMOS LA TABLA CLIENTES*/
CREATE TABLE CLIENTES(
	NUMERO INT NOT NULL,
	NOMBRE VARCHAR(20) NOT NULL,
	DOMICILIO VARCHAR(20) NOT NULL,
	LOCALIDAD VARCHAR(30) NOT NULL,
	PRIMARY KEY(NUMERO));


/*ELIMINAMOS LA TABLA CLIENTES*/
DROP TABLE CLIENTES;


